mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic.base import TemplateView
from exams.views import (dotest, show_result, review, do_signup_quiz, congratulations,
hundred, revise)
from lessons.views import (complete_lesson, mark_lesson_as_complete, take_the_next_quiz,
go_back_to_welcome_student)
from teachers.views import class_list, show_students, see_student_test, add_class
from custom_users.views import (welcome_student, welcome_teacher, signup, signup_form_student,
signup_form_teacher, home, edit_student, edit_teacher, get_help, cancel_help,
student_details_added, teacher_details_added,
ajax_load_teachers, ajax_load_classes, add_school)

urlpatterns = [
    path('get_help', get_help, name='get_help'),
    path('cancel_help', cancel_help, name='cancel_help'),
    path('show_students/<class_name>', show_students, name = 'show_students'),
    path('complete_lesson', complete_lesson, name = 'complete_lesson'),
    path('class_list', class_list, name = 'class_list'),
    path('admin/', admin.site.urls),
    path('dotest', dotest, name='dotest'),
    path('not_teacher', class_list),
    path('finish_test', dotest, name='finish_test'),
    path('show_result/<exam_id>', show_result, name = 'show_result'),
    path('review/<exam_id>', review, name='review'),
    path('welcome_student', welcome_student, name = 'welcome_student'),
    path('welcome_teacher', welcome_teacher, name = 'welcome_teacher'),
    path('users/', include('django.contrib.auth.urls')),
    path('signup', signup, name = 'signup'),
    path('signup_form_student', signup_form_student, name = 'signup_form_student'),
    path('signup_form_teacher', signup_form_teacher, name = 'signup_form_teacher'),
    path('edit_student', edit_student, name = 'edit_student'),
    path('edit_teacher', edit_teacher, name = 'edit_teacher'),
    path('student_details_added', student_details_added, name = 'student_details_added'),
    path('teacher_details_added', teacher_details_added, name = 'teacher_details_added'),
    path('ajax_load_teachers', ajax_load_teachers, name = 'ajax_load_teachers'),
    path('ajax_load_classes', ajax_load_classes, name = 'ajax_load_classes'),
    path('do_signup_quiz', do_signup_quiz, name = 'do_signup_quiz'),
    path('add_school', add_school, name = 'add_school'),
    path('congratulations', congratulations, name='congratulations'),
    path('hundred', hundred, name = 'hundred'),
    path('mark_lesson_as_complete', mark_lesson_as_complete, name = 'mark_lesson_as_complete'),
    path('take_the_next_quiz', take_the_next_quiz, name = 'take_the_next_quiz'),
    path('go_back_to_welcome_student', go_back_to_welcome_student, name = 'go_back_to_welcome_student'),
    path('see_student_test/<exam_id>/<student_id>', see_student_test, name='see_student_test'),
    path('revise', revise, name='revise'),
    path('add_class', add_class, name = 'add_class'),
    path('', home, name='home'),
]

exams/models.py
from django.db import models
from django.contrib.auth.models import User
from custom_users.models import StudentProfile

"""
These are the models form exams and questions.
Students have a Level.
Exams and Lessons also have a level.
Levels can be used to match appropriate exam or lesson to student.
"""
#Exams have a level and a title.
class Exam(models.Model):
    title = models.CharField(max_length = 100, unique = True)
    level = models.IntegerField(default = 1)

    def __str__(self):
        return str(self.level) +" "+self.title

# Questions belong to an exam.
class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    text = models.CharField(max_length=250, unique = True)
    questionimage = models.CharField(max_length=250, null=True, blank = True)
    questiongif = models.CharField(max_length=250, null=True, blank = True)
    questionscript = models.CharField(max_length=250, null=True, blank = True)
    review = models.CharField(max_length=1000)
    reviewimage = models.CharField(max_length=250, null=True, blank = True)
    reviewgif = models.CharField(max_length=250, null=True, blank = True)
    reviewscript = models.CharField(max_length=250, null=True, blank = True)

    def __str__(self):
        return self.text

# Inherits from Question. Written_Answer Style Question
class Written_Question(Question):
    is_written = models.BooleanField(default = True)

    class Meta:
        verbose_name="Written_Question"

# Inherits from Question. Mutliple Choice Style Question
class MCQ_Question(Question):
    is_MCQ = models.BooleanField(default = True)

    class Meta:
        verbose_name="MCQ_Question"

# Inherits from Question. The answer contains a chemical formula
class Formula_Question(Question):
    is_formula = models.BooleanField(default = True)

    class Meta:
        verbose_name="Formula_Question"

# Model for the correct answers or mutiple choice answer options
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    correct = models.BooleanField(default = False)
    correct_spelling = models.BooleanField(default = True)
    correct_answer_to_display = models.BooleanField(default = False)

    def __str__(self):
        return self.text

# Model for storing a student's answers to the quiz
class UserAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user_answer = models.CharField(max_length=1000)
    user = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_answer

# Model to store information about which exams a student has completed
class CompletedExam(models.Model):
    user = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    level = models.IntegerField(default = 1)
    percentage = models.IntegerField(default = 1)
    attempt = models.IntegerField(default = 1)

    def __str__(self):
        return self.user.user.username+" "+self.exam.title

# Model for storing a stuedent's incorrect answers
class IncorrectAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(StudentProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.user.username+ " "+self.question.text

teachers/models.py
from django.db import models
from custom_users.models import TeacherProfile

teachers/forms.py
from django import forms
from custom_users.models import Class_id

class AddClassForm(forms.ModelForm):
    class Meta:
        model = Class_id
        fields = ("name",)

teachers/views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from custom_users.utils import user_is_teacher, user_is_student, have_teacher_details
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from custom_users.models import Class_id, StudentProfile, TeacherProfile
from exams.models import Exam, Question, UserAnswer
from .forms import AddClassForm
from .utils import create_new_class, get_questions_and_student_answers

"""
Checks that the user is a teacher
Shows them a list of the classes that they teach
on the welcome_teacher screen
"""
@login_required
@user_passes_test(user_is_teacher, login_url = 'welcome_student')
@user_passes_test(have_teacher_details, login_url = 'edit_teacher',  redirect_field_name = 'get_teacher_details' )
def class_list(request):
    user = request.user
    teacher = TeacherProfile.objects.get(user_id = user.id)
    classes = Class_id.objects.filter(teacher = teacher)
    return render(request, 'teachers/class_list.html', {
    'user': user,
    'classes':classes,
    })

"""
Checks the user is a teacher
Shows them the students in a class they have clicked on from the
welcome_teacher screen
"""
@login_required
@user_passes_test(user_is_teacher)
@user_passes_test(have_teacher_details, login_url = 'edit_teacher',  redirect_field_name = 'get_teacher_details' )
def show_students(request, class_name):
    user = request.user
    teacher = TeacherProfile.objects.get(user_id = user.id)
    group = Class_id.objects.get(name = class_name, teacher_id = user.id)
    students = StudentProfile.objects.select_related().filter(class_id = group.id)
    return render(request, 'teachers/show_students.html', {
    'group': group,
    'students': students,
    })

"""
Checks the user is a teacher
Shows the questions and students answers to a quiz they have
clicked on from the class overview screen
"""
@login_required
@user_passes_test(user_is_teacher)
@user_passes_test(have_teacher_details, login_url = 'edit_teacher',  redirect_field_name = 'get_teacher_details' )
def see_student_test(request, exam_id, student_id):
    student = StudentProfile.objects.get(user_id = student_id)
    exam = Exam.objects.get(id = exam_id)
    questions = Question.objects.all().filter(exam = exam_id)
    question_and_answer = get_questions_and_student_answers(questions, student)
    return render(request, 'teachers/see_student_test.html', {
    'question_and_answer': question_and_answer,
    'student':student,
    'exam':exam
    })

"""
Checks the user is a teacher
Allows a teacher to add a new teaching group to their
welcome_teacher page
"""
@login_required
@user_passes_test(user_is_teacher)
@user_passes_test(have_teacher_details, login_url = 'edit_teacher',  redirect_field_name = 'get_teacher_details' )
def add_class(request):
    if request.method == 'POST':
        teacher = TeacherProfile.objects.get(user_id = request.user.id)
        form = AddClassForm(request.POST)
        if form.is_valid():
            create_new_class(form, teacher)
            return redirect('welcome_teacher')
        else:
            return render(request, 'teachers/add_class.html', {'form': form})
    else:
        form=AddClassForm()
        return render(request, 'teachers/add_class.html', {'form': form})

teachers/templates/teachers/add_class.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-50" class = "card_left"">
  <div class="card">
    <div class="card-headergreen">Add Class</div>
    <div class="card-body">
      <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
        {{field.label}}<br/>
        {{field}}<br/>
        <br/>
        {% endfor %}
        <a><button type="submit" class="btn btn-success button-right">Add</button></a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

teachers/templates/teachers/class_list.html
{% extends 'base.html' %}

{% block content %}
<h5>Welcome {{user.username}} </h5>

<p>Click on class below to view your student's progress</p>
<p>
{% for class in classes %}
{% load static %}
<a href ="{% url 'show_students' class_name=class.name %}">
<img data-toggle="tooltip" data-placement="top" title={{class.name}} class="img-fluid-2"
 src = "{% static 'images\students-student-svgrepo-com.svg' %}" alt="show_students"/>
</a>
<p>{{class.name}}</p>
{% endfor %}

{% endblock %}

teachers/templates/teachers/see_student_test.html
{% extends 'base.html' %}

{% block content %}
<h5>{{student.user.username}} answers to {{exam.title}}
<a href = "{% url 'show_students' class_name=student.class_id.name %}"><button type="button" class="btn btn-success button-right">
Back To Student List </button></a>
</h5>

{% for key, value in question_and_answer.items %}
    {% if key.get_type == exams.Written_Question %}
        <strong>Q&nbsp</strong>{{key.text|safe}}<br/>
        {% if key.questionimage %}
            <br/><img class="question_img_full" src = "{{key.questionimage}}"/><br/>
        {% endif %}
        {% if key.questiongif %}
            <br/><img class="question_gif_full" src = "{{key.questiongif}}"/><br/>
        {% endif %}
        {% if key.questionscript %}
            <br/>{{key.questionscript|safe}}<br/>
        {% endif %}
        <!--DO NOT MARK USER INPUT AS SAFE-->
        Students answer: {{value.user_answer}}
        <br/><br/>
    {% else %}
        <strong>Q&nbsp</strong>{{key.text|safe}}<br/>
        {% if key.questionimage %}
            <br/><img class="question_img_full" src = "{{key.questionimage}}"/><br/>
        {% endif %}
        {% if key.questiongif %}
            <br/><img class="question_gif_full" src = "{{key.questiongif}}"/><br/>
        {% endif %}
        {% if key.questionscript %}
            <br/>{{key.questionscript|safe}}<br/>
        {% endif %}
        Students answer: {{value.user_answer|safe}}
        <br/><br/>
    {% endif %}
{% endfor %}

{% endblock %}

teachers/templates/teachers/show_students.html
{% extends 'base_with_refresh.html' %}

{% block content %}
<h5>Class: {{group.name}}
<a href = "{% url 'welcome_teacher' %}"><button type="button" class="btn btn-success button-right">
Back To Class Lists</button></a>
</h5>
<table class = "table" id = "mytable">
  <thead class = "thead-light">
    <tr>
      <th style = "width: 15%;">Student</th>
      <th style = "width: 10%;">Starting Level</th>
      <th style = "width: 10%;">Needs Help</th>
      <th style = "width: 10%;">Current Level</th>
      <th style = "width: 10%;">Progress</th>
      <th style = "width: 35%;">Quizzes</th>
      <th style = "width: 10%;">Percentage</th>
    </tr>
  </thead>
{% for student in students %}
<tr>
<td>{{student.user.username}}</td>
<td>{{student.starting_level}}</td>
{% if student.needs_help == True %}
<td>&#9989;</td>
{% else %}
<td> </td>
{% endif %}
{% if student.level < 17 %}
    <td>{{student.level}}</td>
{% else%}
    <td>Finished</td>
{% endif %}
{% if student.progress == 1 %}
<td><svg height="22" width="22">
  <circle cx="11" cy="11" r="10" stroke="white" stroke-width="3" fill="green" />
</svg></td>
{% elif student.progress == 2  %}
<td> <svg height="22" width="22">
  <circle cx="11" cy="11" r="10" stroke="white" stroke-width="3" fill="yellow" />
</svg></td>
{% else %}
<td><svg height="22" width="22">
  <circle cx="11" cy="11" r="10" stroke="white" stroke-width="3" fill="red" />
</svg></td>
{% endif %}
<td>
{% for completedexam in student.completedexam_set.all %}
{{completedexam.exam.title}}<br/>
{% endfor %}
</td>
<td>
{% for completedexam in student.completedexam_set.all %}
<a class = "bluelink"
  href = "{% url 'see_student_test' exam_id=completedexam.exam.id student_id=student.user_id %}">
  {{completedexam.percentage}}</a><br/>
{% endfor %}
</td>
</tr>
{% endfor %}
</table>
{% endblock %}